services:
  server:
    container_name: server
    image: ${IMAGE:-beneburg:local}
    platform: ${PLATFORM:-linux/amd64}
    environment:
      - SQLITE_PATH=/data/beneburg.db
      - BOT_TOKEN
      - ONLY_MAKE_MIGRATIONS
      - NO_AUTH
      - ENVIRONMENT
      - TRUSTED_PROXY
      - ADMIN_ID
      - GROUP_ID
      - INVITE_LINK
      - DOMAIN
    build:
      context: .
      dockerfile: "deploy/server/${DOCKER_FILE:-deploy}.Dockerfile"
      no_cache: true
      args:
        - ENVIRONMENT
    volumes:
      - sqlite_data:/data
      - letsencrypt:/root/.cache
      - ssl:/etc/ssl/certs
    ports:
      - "8080:8080"
      - "2345:2345"
    restart: always

volumes:
  sqlite_data: {}
  letsencrypt: {}
  ssl: {}
