package database

import (
	"context"
	"database/sql"
	"fmt"
)

// PostgreSQL releases this migration lock automatically if the transaction or
// its connection ends unexpectedly.
const migrationLockID int64 = 715723661091

const postgresSchema = `
CREATE TABLE schema_migrations (version BIGINT PRIMARY KEY);
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ,
    telegram_id BIGINT NOT NULL UNIQUE,
    username TEXT,
    first_name TEXT NOT NULL DEFAULT '',
    last_name TEXT,
    status TEXT NOT NULL DEFAULT 'new'
);
CREATE TABLE tokens (
    uuid UUID NOT NULL UNIQUE,
    user_telegram_id BIGINT PRIMARY KEY REFERENCES users(telegram_id),
    expire_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE forms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ,
    user_telegram_id BIGINT NOT NULL REFERENCES users(telegram_id),
    name TEXT NOT NULL,
    birth_date DATE,
    gender TEXT NOT NULL DEFAULT 'undefined',
    about TEXT,
    hobbies TEXT,
    work TEXT,
    education TEXT,
    cover_letter TEXT,
    contacts TEXT,
    status TEXT NOT NULL DEFAULT 'new'
);
CREATE INDEX forms_user_created_at_idx ON forms(user_telegram_id, created_at DESC);
CREATE INDEX tokens_uuid_idx ON tokens(uuid);
INSERT INTO schema_migrations(version) VALUES (1);
`

const scheduledJobsMigration = `
CREATE TABLE scheduled_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    job_type TEXT NOT NULL,
    cron_expression TEXT NOT NULL,
    timezone TEXT NOT NULL DEFAULT 'Europe/Moscow',
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    next_run_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX scheduled_jobs_due_idx ON scheduled_jobs(next_run_at) WHERE enabled;

CREATE TABLE job_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheduled_job_id BIGINT NOT NULL REFERENCES scheduled_jobs(id) ON DELETE CASCADE,
    scheduled_for TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('running', 'succeeded', 'failed')),
    attempts INTEGER NOT NULL DEFAULT 1 CHECK (attempts > 0),
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,
    error_text TEXT,
    UNIQUE (scheduled_job_id, scheduled_for)
);
CREATE INDEX job_runs_finished_at_idx ON job_runs(finished_at) WHERE status IN ('succeeded', 'failed');
INSERT INTO schema_migrations(version) VALUES (2);
`

const birthDateMigration = `
ALTER TABLE forms DROP COLUMN IF EXISTS age;
ALTER TABLE forms ADD COLUMN IF NOT EXISTS birth_date DATE;
INSERT INTO schema_migrations(version) VALUES (3);
`

func migratePostgres(ctx context.Context, connection *sql.DB) error {
	transaction, err := connection.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("start PostgreSQL migration: %w", err)
	}
	defer transaction.Rollback()
	if _, err := transaction.ExecContext(ctx, `SELECT pg_advisory_xact_lock($1)`, migrationLockID); err != nil {
		return fmt.Errorf("lock PostgreSQL migrations: %w", err)
	}
	var exists bool
	err = transaction.QueryRowContext(ctx, `SELECT to_regclass('schema_migrations') IS NOT NULL`).Scan(&exists)
	if err != nil {
		return fmt.Errorf("check PostgreSQL schema: %w", err)
	}
	if !exists {
		if _, err := transaction.ExecContext(ctx, postgresSchema); err != nil {
			return fmt.Errorf("create PostgreSQL schema: %w", err)
		}
	}
	var version int
	if exists {
		err = transaction.QueryRowContext(ctx, `SELECT COALESCE(MAX(version), 0) FROM schema_migrations`).Scan(&version)
		if err != nil {
			return fmt.Errorf("read PostgreSQL schema version: %w", err)
		}
	} else {
		version = 1
	}
	if version > 3 {
		return fmt.Errorf("unsupported PostgreSQL schema version %d", version)
	}
	if version < 2 {
		if _, err := transaction.ExecContext(ctx, scheduledJobsMigration); err != nil {
			return fmt.Errorf("apply PostgreSQL migration 2: %w", err)
		}
	}
	if version < 3 {
		if _, err := transaction.ExecContext(ctx, birthDateMigration); err != nil {
			return fmt.Errorf("apply PostgreSQL migration 3: %w", err)
		}
	}
	return transaction.Commit()
}
