package database

import (
	"context"
	"database/sql"
	"fmt"
)

// The importer and the migration runner share this lock. PostgreSQL releases it
// automatically if the transaction or its connection ends unexpectedly.
const migrationLockID int64 = 715723661091

const postgresSchema = `
CREATE TABLE schema_migrations (version BIGINT PRIMARY KEY);
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ,
    telegram_id BIGINT NOT NULL UNIQUE,
    username TEXT,
    first_name TEXT NOT NULL DEFAULT '',
    last_name TEXT,
    status TEXT NOT NULL DEFAULT 'new'
);
CREATE TABLE tokens (
    uuid UUID NOT NULL UNIQUE,
    user_telegram_id BIGINT PRIMARY KEY REFERENCES users(telegram_id),
    expire_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE forms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ,
    user_telegram_id BIGINT NOT NULL REFERENCES users(telegram_id),
    name TEXT NOT NULL,
    age INTEGER,
    gender TEXT NOT NULL DEFAULT 'undefined',
    about TEXT,
    hobbies TEXT,
    work TEXT,
    education TEXT,
    cover_letter TEXT,
    contacts TEXT,
    status TEXT NOT NULL DEFAULT 'new'
);
CREATE INDEX forms_user_created_at_idx ON forms(user_telegram_id, created_at DESC);
CREATE INDEX tokens_uuid_idx ON tokens(uuid);
CREATE TABLE sqlite_imports (
    source_sha256 TEXT PRIMARY KEY,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    users_count BIGINT NOT NULL,
    tokens_count BIGINT NOT NULL,
    forms_count BIGINT NOT NULL
);
INSERT INTO schema_migrations(version) VALUES (1);
`

func (d *database) ImportCompleted(ctx context.Context) (bool, error) {
	if !d.postgres {
		return false, fmt.Errorf("import marker requires PostgreSQL")
	}
	var count int64
	var exists bool
	err := d.db.QueryRowContext(ctx, `SELECT to_regclass('sqlite_imports') IS NOT NULL`).Scan(&exists)
	if err != nil {
		return false, fmt.Errorf("check SQLite import marker: %w", err)
	}
	if !exists {
		return false, nil
	}
	err = d.db.QueryRowContext(ctx, `SELECT count(*) FROM sqlite_imports`).Scan(&count)
	if err != nil {
		return false, fmt.Errorf("read SQLite import marker: %w", err)
	}
	return count == 1, nil
}

func migratePostgres(ctx context.Context, connection *sql.DB) error {
	transaction, err := connection.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("start PostgreSQL migration: %w", err)
	}
	defer transaction.Rollback()
	if _, err := transaction.ExecContext(ctx, `SELECT pg_advisory_xact_lock($1)`, migrationLockID); err != nil {
		return fmt.Errorf("lock PostgreSQL migrations: %w", err)
	}
	var exists bool
	err = transaction.QueryRowContext(ctx, `SELECT to_regclass('schema_migrations') IS NOT NULL`).Scan(&exists)
	if err != nil {
		return fmt.Errorf("check PostgreSQL schema: %w", err)
	}
	if !exists {
		return fmt.Errorf("PostgreSQL schema is absent; run the SQLite import release first")
	}
	var version int
	err = transaction.QueryRowContext(ctx, `SELECT COALESCE(MAX(version), 0) FROM schema_migrations`).Scan(&version)
	if err != nil {
		return fmt.Errorf("read PostgreSQL schema version: %w", err)
	}
	if version != 1 {
		return fmt.Errorf("unsupported PostgreSQL schema version %d", version)
	}
	return transaction.Commit()
}
